"""Migrate fix

Revision ID: 183c19b9f61e
Revises: 3cf61f7c01c7
Create Date: 2024-12-17 20:32:24.890662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '183c19b9f61e'
down_revision = '3cf61f7c01c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint('bookings_leaver_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('bookings_listing_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('bookings_sitter_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['leaver_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'listings', ['listing_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['sitter_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_constraint('listings_leaver_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('listings_sitter_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['sitter_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'users', ['leaver_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint('messages_receiver_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('messages_listing_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('messages_sender_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['sender_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'listings', ['listing_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['receiver_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_constraint('notification_listing_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('notification_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'listings', ['listing_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('priceproposal', schema=None) as batch_op:
        batch_op.drop_constraint('priceproposal_proposer_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('priceproposal_listing_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'listings', ['listing_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['proposer_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_constraint('review_booking_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('review_reviewee_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('review_reviewer_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'bookings', ['booking_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['reviewee_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['reviewer_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_picture')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture', sa.VARCHAR(length=120), autoincrement=False, nullable=True))

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('review_reviewer_id_fkey', 'users', ['reviewer_id'], ['id'])
        batch_op.create_foreign_key('review_reviewee_id_fkey', 'users', ['reviewee_id'], ['id'])
        batch_op.create_foreign_key('review_booking_id_fkey', 'bookings', ['booking_id'], ['id'])

    with op.batch_alter_table('priceproposal', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('priceproposal_listing_id_fkey', 'listings', ['listing_id'], ['id'])
        batch_op.create_foreign_key('priceproposal_proposer_id_fkey', 'users', ['proposer_id'], ['id'])

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('notification_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key('notification_listing_id_fkey', 'listings', ['listing_id'], ['id'])

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('messages_sender_id_fkey', 'users', ['sender_id'], ['id'])
        batch_op.create_foreign_key('messages_listing_id_fkey', 'listings', ['listing_id'], ['id'])
        batch_op.create_foreign_key('messages_receiver_id_fkey', 'users', ['receiver_id'], ['id'])

    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('listings_sitter_id_fkey', 'users', ['sitter_id'], ['id'])
        batch_op.create_foreign_key('listings_leaver_id_fkey', 'users', ['leaver_id'], ['id'])

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('bookings_sitter_id_fkey', 'users', ['sitter_id'], ['id'])
        batch_op.create_foreign_key('bookings_listing_id_fkey', 'listings', ['listing_id'], ['id'])
        batch_op.create_foreign_key('bookings_leaver_id_fkey', 'users', ['leaver_id'], ['id'])

    # ### end Alembic commands ###
